language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
env:
  matrix:
  - secure: KuxGv0QE5Gzzh1uYxqTeGAlnu7IPWdefXQFMkn0Fl2QjzVixtiUEMRkD/hI/AVerv2+u4KuIecGKRlpp85HB3A8Ig3m21Wl0bhmYCCMjxE75Fii7CZaZbso0VGlacOyV/ZxMJGV+dnNCt0Rhlse3v8l3W9QuIl3anAgZd/biNymvxU1LR3TUPHoZ8JnFUXGRCF+PKQYSz2z4AFNule8xrBq6xGYTn6BzGLl/Bji0aD8ImjKgkWdQEnUw6o/R3GyK248gt+sRFEs9xXD/OPsc3VENdNq1/oyrtIenvEtYko0seTWNl0W7HpwUyva+r7ICbavsnaISQpUsRQBEKSdal1FbXOrz6rrPDLUWYDLfQxYQEqsB1q/CxLUjGrsr55yYMF292FSq/pazxi/+YHqkhD2qd4+ZCbdXvT/HOXk4PvkewRot5QfDZLde/Vr+9UUWA21WoQ8st/Xaq2D0Iinclms/BTpmxp8NV7ObHUTpu1TWbktH0FvnkLSDrExQI/ygd2kAWUszqKCAfLPlLcYAW4YlG5AxSMeHTH9s9VLMn6nYN5S0JeaEVI8cVIa9YIBDQVqG98eY80xYpdNxzCUr8+nj4RvPvoKGT2u5pcfB1QLQJJzWc+ZsqdmSEmaPiOvyoRwkY1VlYFnHZKcRh7vLb8CbRvut3Tpn8clojntr+Ko=
  - secure: kFSeoB3XgOG8busHERa5jvns76ezQfBWOmLZ46AZo9fsBOw8/jW2ib12r0VIIoyXbwt7F0vesvN5ChwtdtFZz2sRp+dWpjWramgFz6NkOP6dJPm6C06vrUFOgxKCNOSDA2jS9/uAKGIf4E6l2QzZqlTfy3HJLyGX95zkA1Cvj1bJrHtRmRWrMvDf2tTEHDYeF2ZuS2aNCxqHdvXmAr8meHdG0zALzR53tk5wrh3euA5R8OnACMoj9ImEzEBev4TwdMYoZhvGoguq9P9UeDevzijzrk7uSBOAyA6/WBch57UVYMfYMgjAhrCDfdrtoCw2fw1mGN4L3g7tSj1Nl5Lq7t1F/IaNXxf5AC2iq64pVMeXFOEMIAqaxdzjjShO+XMXaubtk2IQwDIPO8CaDFR21CYL02cYiL0F0gOd9deJVbiZQiv+swgPG+p+C6bAKKb4EyjfXNK0GA9jOPKWOpFCdx1jLuU+g2xU4cyxPs0EvCdxbAlS0uiHA21kYI8B3X/IkpkJguySO/y1iThIJrLI2Vzsket0ZE/ddqg/a/Qqgm6+MAMhvJZnYquTxm9HNkDPQzSJj7gx2uZkqUYao0J7EQuG4WiYH3vsq2Thw64Al5xe2Ibx8H11h5HxYKm/JdJVgg3qthyiBDseudfntYgRXtjMk5sMDh/PMBHMGwlNlH8=
before_install: pip install pytest pytest-cov
install: pip install -r requirements.txt
script: python -m pytest --cov=usajobs/ tests
after_success: bash <(curl -s https://codecov.io/bash)
