language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
env:
  secure: "Bgg1D8sCC7GfMtjJk1qdbVIyPe+bxpVDHZ10OLJQ6MET3TjC59MRpu2tSneM/u4Qm8XSVHIKarmp0N23rYB9Sq3cRkbCRPvLHJTS9DMHCOKJlwHxjhY0zI6RUTUPtp5ydBOMdrVkkNIY9KrxaBpU6aY5x2BJP9iKcxhd/2eZ5nP6HZ50m8QFCIN7jS0ID8pj8P8hcocGnyy5jdVsOkqMiM9eeYG56piUIHC3swCTU4S3R+wofJP/GOnMZuaWN3Qbq1akkTTc9OQL2ZeZu3wlQYKcMjThB1QvAytcN9Nzm63zgZC1dn2n/tuaA2nFCtadYUBWsw4mDz/ri6pSLJ6F6p+LQ/JcLd5+PTzhnBHQytpcaD52ImjgeXkbx37LLW506qmiuhreEmJDn85k2ABoH/0FCM7GeOAoAtkG5LW5EJ4TlW0V4vjqszH0H15tgyUjRFbbyJ7RzGBpoNab3GcJcIy3CwIEQX19N7chpfwlzDMDRSdXcXRbZtX6wKqboHiw0I7QcNmLqPi8DZclpftfApqKt8i4Zp8bHi7TpMiFrFhPBt5tkNmv6xghw/wy1Q7dMFXYTwKKNsKPWl+i+R8TuC0Vp1FxZG2wZeVACG+NE2EDIjrJNzulJ5Dj5JWW52+YfiiHM44s8VsGum656I6TNgW6zEMnz7+LdWJc6rqUK1A="
before_install: pip install pytest pytest-cov
install: pip install -r requirements.txt
script: python -m pytest --cov=usajobs/ tests
after_success: bash <(curl -s https://codecov.io/bash)
